[package]
name = "b64"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
base64-simd = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util", "fs"] }
base64 = "0.22"

[features]
simd = []
simd-avx2 = []
simd-sse2 = []
simd-neon = []

default = []

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
memmap2 = "0.9"
rand = "0.8"

[[bench]]
name = "b64_bench"
harness = false
