[package]
name = "b64"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
base64-simd = { version = "0.8", optional = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util"] }
base64 = "0.22"

[features]
simd = ["base64-simd"]
simd-avx2 = ["simd"]
simd-sse2 = ["simd"]
simd-neon = ["simd"]

default = ["simd"] # or empty if you want scalar-only by default

[dev-dependencies]
criterion = "0.5"
memmap2 = "0.9"
rand = "0.8"

[[bench]]
name = "b64_bench"
harness = false
